[program:yii-migrate]
command=/app/yii migrate --interactive=0
autostart=%(ENV_SUPERVISOR_START_MIGRATION)s
autorestart=false
startretries=0
startsecs=0
priority=60
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
