name: Docker Image CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
       include:
         - php-base-image-version: "8.2-fpm"
           dockerfile-flavour: "debian"
           compose-file: "docker-compose.yml,docker-compose.fpm-nginx.yml"
           experimental: false
      fail-fast: false
    env:
      COMPOSE_FILE: ${{ matrix.compose-file }}
      COMPOSE_PATH_SEPARATOR: ","
      PHP_IMAGE_NAME: "ghcr.io/deliverymatch/yii2-php"
      PHP_BASE_IMAGE_VERSION: ${{ matrix.php-base-image-version }}
      DOCKERFILE_FLAVOUR: ${{ matrix.dockerfile-flavour }}
      X_LEGACY_GD_LIB: ${{ matrix.legacy-gd-lib }}
      PECL_XDEBUG_INSTALL_SUFFIX: ${{ matrix.pecl-xdebug-suffix }}
      PECL_MONGODB_INSTALL_SUFFIX: ${{ matrix.pecl-mongodb-suffix }}
      PECL_IMAGICK_INSTALL_SUFFIX: ${{ matrix.pecl-imagick-suffix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set version suffix (tags)
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "PHP_IMAGE_VERSION_SUFFIX=-${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Set version suffix (master/latest)
      if: (github.ref == 'refs/heads/master' && (github.event_name != 'workflow_dispatch' && github.event_name != 'schedule'))
      run: echo "PHP_IMAGE_VERSION_SUFFIX=-latest" >> $GITHUB_ENV
    - name: Install
      env:
        TEST_YII_VERSION: "5df412df2c9b4e60e7ec84008693b94ae472eae6"
      run: |
        git clone https://github.com/yiisoft/yii2 _host-volumes/yii2
        pushd _host-volumes/yii2 && git checkout ${TEST_YII_VERSION} && popd
        cp .env-dist .env
    - name: Print Info
      run: |
        pwd
        docker version
        docker info
        docker compose version
    - name: Build Image
      uses: docker/bake-action@v6
      with:
        files: ${{ matrix.compose-file }}
        load: true
        set: |
          *.platform=linux/amd64
          *.args.X_LEGACY_GD_LIB=${{ matrix.legacy-gd-lib }}
    - name: Test
      run: |
        docker compose run --rm php-min php -v
        docker compose run --rm php-min php -v | grep "Xdebug" && exit 1
        docker compose run --rm php-min php /tests/requirements.php
        docker compose run --rm php-dev php /tests/requirements.php
        docker compose run --rm -w /yii2 php-dev composer update --prefer-dist
        docker compose run --rm -w /yii2 php-dev php -d error_reporting="E_ALL ^ E_DEPRECATED" vendor/bin/phpunit tests/framework/ --exclude db
        docker compose run --rm -e PHP_ENABLE_XDEBUG=1 php-dev php -v | grep "Xdebug" || exit 1
        docker images
    - name: Login to Docker
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push docker image (amd64 master/latest)
      if: (github.ref == 'refs/heads/master' && (github.event_name != 'workflow_dispatch' && github.event_name != 'schedule'))
      uses: docker/bake-action@v6
      with:
        files: ${{ matrix.compose-file }}
        push: true
        set: |
          *.platform=linux/amd64
    - name: Build and push docker image (amd64,arm64)
      if: |
          startsWith(github.ref, 'refs/tags/') ||
          (github.ref == 'refs/heads/master' && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'))
      uses: docker/bake-action@v6
      with:
        files: ${{ matrix.compose-file }}
        push: true
        set: |
          *.platform=linux/amd64,linux/arm64
